#!/bin/bash

set -uo pipefail

trap ctrl_c INT

ctrl_c() {
	echo "Aborted."
	rm -f tmp
	exit
}

one() {
	input="tests/input$1.txt"
	output="tests/output$1.txt"
	run="python numbrix.py $input"

	echo "$input"

	case "$2" in
		"timer")
			time $run > /dev/null
			;;

		"output")
			$run > tmp
			;;

		"full")
			time $run > tmp
			;;
	esac

	if [ -f tmp ]; then
		cat tmp
		diff tmp "$output"
		rm -f tmp
	fi

	echo ""
}

timer() {
	for i in {0..10}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

output() {
	for i in {0..10}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

full() {
	for i in {0..10}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

"$@"
