#!/bin/bash

set -uo pipefail

trap ctrl_c INT

ctrl_c() {
	echo "Aborted."
	rm -f tmp
	exit
}

one() {
	input="tests/input$1.txt"
	output="tests/output$1.txt"
	file="numbrix.py"
	profile="-m profile -s tottime"

	echo "$input"

	case "$2" in
		"timer")
			time python $file $input > /dev/null
			;;

		"output")
			python $file $input > tmp
			;;

		"profile")
			python $profile $file $input | head -n 30
			;;

		"full")
			time python $file $input > tmp
			;;
	esac

	if [ -f tmp ]; then
		cat tmp
		diff tmp "$output"
		rm -f tmp
	fi

	echo ""
}

timer() {
	for i in {0..13}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

output() {
	for i in {0..13}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

profile() {
	for i in {0..13}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

full() {
	for i in {0..13}; do
		one "$i" "${FUNCNAME[0]}"
	done
}

"$@"
